# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.TOKEN}}
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    allow:
      # Allow updates for React and any packages starting "@mule-app"
      - dependency-name: "@mule-app*"
    commit-message:
      # Prefix all commit messages with "Mule dependencies npm"
      prefix: "@mule-app"
    labels:
      - "@mule-app"
      - "dependency-auto-update"
    rebase-strategy: "auto"
    registries:
      - npm-github
    versioning-strategy: increase
    schedule:
      interval: "daily"
      time: "09:00"
